# Generated by Django 5.0.7 on 2024-07-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_api', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('INPR', 'In_Progress'), ('FINI', 'Finished')], default='TODO', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BAE', 'Back_End'), ('FRE', 'Front_End'), ('IOS', 'Ios'), ('AND', 'Android')], max_length=3),
        ),
    ]
